In [5]:
import torch
import timm
from torch import nn, optim
from torch.utils.data import DataLoader, Subset
from torchvision import datasets, transforms
from torchvision.transforms import ToTensor, Normalize, Resize, Compose
from sklearn.model_selection import train_test_split
from torchvision.datasets import ImageFolder
from collections import defaultdict
from torch.utils.data import random_split
import time
from torchinfo import summary
import numpy as np
import pandas as pd
from transformers import MobileViTForImageClassification

In [2]:
import torch
from torchvision import datasets, transforms
from torch.utils.data import DataLoader
import random

class RandomOneTransform:
    def __init__(self, transforms):
        self.transforms = transforms

    def __call__(self, img):
        # Randomly choose one transformation to apply
        transform = random.choice(self.transforms)
        return transform(img)

In [6]:
def save_model(model, filename="model_state_dict.pth"):
  torch.save(model, f"{filename}.pth")
  torch.save(model.state_dict(), f"s_{filename}.pth")
    

In [7]:

def validate(device, model, val_loader):
    model.to(device).float()
    model.eval()
    num_classes = len(val_loader.dataset.classes)  
    confusion_matrix = np.zeros((num_classes, num_classes), dtype=int)

    with torch.no_grad():
        correct = 0
        total = 0
        class_correct = {}
        class_total = {}
        false_positives = {}
        false_negatives = {}

        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images).logits
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

            for label, prediction in zip(labels, predicted):
                confusion_matrix[label.item(), prediction.item()] += 1  # Update the confusion matrix
                if label == prediction:
                    class_correct[label.item()] = class_correct.get(label.item(), 0) + 1
                else:
                    false_negatives[label.item()] = false_negatives.get(label.item(), 0) + 1
                    false_positives[prediction.item()] = false_positives.get(prediction.item(), 0) + 1

                class_total[label.item()] = class_total.get(label.item(), 0) + 1

        # Calculate precision and recall
        precision_list = []
        recall_list = []

        for class_id in class_total.keys():
            tp = class_correct.get(class_id, 0)
            fp = false_positives.get(class_id, 0)
            fn = false_negatives.get(class_id, 0)

            precision = tp / (tp + fp) if (tp + fp) > 0 else 0
            recall = tp / (tp + fn) if (tp + fn) > 0 else 0

            precision_list.append(precision)
            recall_list.append(recall)

        # Calculate overall precision, recall
        overall_precision = sum(precision_list) / len(precision_list) if len(precision_list) > 0 else 0
        overall_recall = sum(recall_list) / len(recall_list) if len(recall_list) > 0 else 0
        accuracy = 100 * correct / total

        print(f'Accuracy: {accuracy:.2f}%')
        print(f'Precision: {overall_precision:.2f}')
        print(f'Recall: {overall_recall:.2f}')

        return accuracy, overall_precision, overall_recall, confusion_matrix
    

In [8]:
def train(device, model, train_loader, criterion, optimizer, num_epochs):
    model.to(device).float()
    model.train()
    train_losses = []
    start = time.time()
    
    for epoch in range(num_epochs):
        print(f'Start epoch {epoch+1}/{num_epochs}')
        running_loss = 0.0
        train_correct = 0
        train_total = 0

        for images, labels in train_loader:
            images, labels = images.to(device), labels.to(device)
            optimizer.zero_grad()
            outputs = model(images).logits
            loss = criterion(outputs, labels)
            loss.backward()
            optimizer.step()

            running_loss += loss.item()
            _, predicted = torch.max(outputs, 1)
            train_total += labels.size(0)
            train_correct += (predicted == labels).sum().item()

        epoch_loss = running_loss / len(train_loader)
        train_losses.append(epoch_loss)
        train_accuracy = train_correct / train_total
        print(f'Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}, Accuracy: {train_accuracy:.2f}')

    end = time.time()
    computation_time = end - start 
    print(f'Training completed in {(end - start):.2f} seconds')
    print(f'Training accuracy: {train_accuracy:.2f}')
    print('--------------------------------')

    return train_accuracy, train_losses, computation_time


In [14]:
device = "mps" if torch.backends.mps.is_available() else "cpu"

 
model_name = 'mobilevit-small'
learning_rate = 0.001
batch_size = 64
is_pretrained = True
is_pretrained_str = "pretrained" if is_pretrained else "not_pretrained"
file_name = f"{model_name}-lr_{learning_rate}-batch_{batch_size}-pretrained_{is_pretrained_str}"
num_classes = 8


model = MobileViTForImageClassification.from_pretrained("apple/mobilevit-small")
    

for param in model.parameters():
    param.requires_grad = False

num_classes = 8
model.classifier = nn.Sequential(
    nn.Linear(model.classifier.in_features, num_classes)
).to(device)

# Define the loss function and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr= learning_rate)

# Define path to PlantVillage dataset
dataset_path_training = '../../dataset-tomatoes/train'

# Load the PlantVillage dataset with appropriate transforms

data_transforms = transforms.Compose([
    RandomOneTransform([
        transforms.RandomHorizontalFlip(),
        transforms.ColorJitter(brightness=0.5),
        transforms.ColorJitter(contrast=0.5),
        transforms.ColorJitter(saturation=0.5),
        transforms.RandomRotation(45),
        transforms.RandomResizedCrop(size=(224, 224), scale=(0.8, 1.0), ratio=(0.75, 1.33))
    ]),
    Resize((224, 224)),
    ToTensor(),
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])

data_transforms_validation_test = transforms.Compose([
    Resize((224, 224)),
    ToTensor(),
    Normalize(mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225])
])


# Ebable training mode

# Fine-tune the model
num_epochs = 25

# freeze conv_1x1_exp layers
for param in model.mobilevit.conv_1x1_exp.parameters():
    param.requires_grad = True

print("Training on:", device, ", pretrained:", is_pretrained_str)
print(f"Number of parameters in the model: {sum(p.numel() for p in model.parameters())}")
print(f"Number of trainable parameters in the model: {sum(p.numel() for p in model.parameters() if p.requires_grad)}")

total_params = sum(p.numel() for p in model.parameters())
total_trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

for name, param in model.named_parameters():
    print(name, param.requires_grad)

Training on: mps , pretrained: pretrained
Number of parameters in the model: 4942760
Number of trainable parameters in the model: 108808
mobilevit.conv_stem.convolution.weight False
mobilevit.conv_stem.normalization.weight False
mobilevit.conv_stem.normalization.bias False
mobilevit.encoder.layer.0.layer.0.expand_1x1.convolution.weight False
mobilevit.encoder.layer.0.layer.0.expand_1x1.normalization.weight False
mobilevit.encoder.layer.0.layer.0.expand_1x1.normalization.bias False
mobilevit.encoder.layer.0.layer.0.conv_3x3.convolution.weight False
mobilevit.encoder.layer.0.layer.0.conv_3x3.normalization.weight False
mobilevit.encoder.layer.0.layer.0.conv_3x3.normalization.bias False
mobilevit.encoder.layer.0.layer.0.reduce_1x1.convolution.weight False
mobilevit.encoder.layer.0.layer.0.reduce_1x1.normalization.weight False
mobilevit.encoder.layer.0.layer.0.reduce_1x1.normalization.bias False
mobilevit.encoder.layer.1.layer.0.expand_1x1.convolution.weight False
mobilevit.encoder.layer.1.

In [15]:
train_dataset = ImageFolder(root=dataset_path_training, transform=data_transforms)
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)

train_accuracy, train_losses, computation_time = train(device, model, train_loader, criterion, optimizer, num_epochs=25)

save_model(model, file_name)

Start epoch 1/25
Epoch 1/25, Loss: 0.8199, Accuracy: 0.78
Start epoch 2/25
Epoch 2/25, Loss: 0.3652, Accuracy: 0.89
Start epoch 3/25
Epoch 3/25, Loss: 0.2840, Accuracy: 0.91
Start epoch 4/25
Epoch 4/25, Loss: 0.2484, Accuracy: 0.92
Start epoch 5/25
Epoch 5/25, Loss: 0.2204, Accuracy: 0.93
Start epoch 6/25
Epoch 6/25, Loss: 0.2027, Accuracy: 0.93
Start epoch 7/25
Epoch 7/25, Loss: 0.1823, Accuracy: 0.94
Start epoch 8/25
Epoch 8/25, Loss: 0.1658, Accuracy: 0.95
Start epoch 9/25
Epoch 9/25, Loss: 0.1617, Accuracy: 0.95
Start epoch 10/25
Epoch 10/25, Loss: 0.1526, Accuracy: 0.95
Start epoch 11/25
Epoch 11/25, Loss: 0.1503, Accuracy: 0.95
Start epoch 12/25
Epoch 12/25, Loss: 0.1405, Accuracy: 0.95
Start epoch 13/25
Epoch 13/25, Loss: 0.1284, Accuracy: 0.96
Start epoch 14/25
Epoch 14/25, Loss: 0.1186, Accuracy: 0.96
Start epoch 15/25
Epoch 15/25, Loss: 0.1181, Accuracy: 0.96
Start epoch 16/25
Epoch 16/25, Loss: 0.1062, Accuracy: 0.96
Start epoch 17/25
Epoch 17/25, Loss: 0.1044, Accuracy: 0.9

In [ ]:
validation_dataset = ImageFolder(root='../dataset-tomatoes/validation', transform=data_transforms_validation_test)
validation_loader = DataLoader(validation_dataset, batch_size=batch_size, shuffle=True)

try:
    validation_accuracy, validation_precision, validation_recall, confusion_matrix = validate(device, model, validation_loader)
    print(f"Validation Accuracy: {validation_accuracy}%")
    print(f"Validation Precision: {validation_precision}")
    print(f"Validation Recall: {validation_recall}")
    print(f"Confusion Matrix:\n{confusion_matrix}")
except RuntimeError as e:
    print(f"Runtime error: {e}")

Accuracy: 95.32%
Precision: 0.94
Recall: 0.93
Validation Accuracy: 95.32293986636971%
Validation Precision: 0.9408091604501988
Validation Recall: 0.9289221996433807
Confusion Matrix:
[[224   2   1   1   5   1   0   1]
 [  3 112   8   1   4   2   0   1]
 [  0   5 203   1   0   0   1   0]
 [  1   1   3 112   0   3   0   0]
 [  5   9   2   8 184   2   0   0]
 [  0   1   0   0   0 623   0   0]
 [  0   1   3   0   1   1  57   3]
 [  0   1   0   1   0   1   0 197]]


In [ ]:
test_dataset = ImageFolder(root='../dataset-tomatoes/test', transform=data_transforms_validation_test)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=True)
test_accuracy, test_precision, test_recall, test_matrix = validate(device, model, validation_loader)

Accuracy: 95.32%
Precision: 0.94
Recall: 0.93


In [9]:
load_model = torch.load("/Users/lorenzoperinello/Desktop/Uni/VCS/vcs-tomatoes/models-for-raspberry/fine-tuning-few-layers/mobilevit-small/mobilevit-small-lr_0.001-batch_64-pretrained_pretrained.pth")
device = "mps" if torch.backends.mps.is_available() else "cpu"
load_model.to(device)

model_scripted = torch.jit.script(load_model)
model_scripted.save("mobilevit-small.pt")

GFLOPs: 3.0640


/opt/homebrew/lib/python3.11/site-packages/torchprofile/profile.py:22: UserWarning: No handlers found: "aten::silu". Skipped.
  warnings.warn('No handlers found: "{}". Skipped.'.format(
/opt/homebrew/lib/python3.11/site-packages/torchprofile/profile.py:22: UserWarning: No handlers found: "aten::reshape". Skipped.
  warnings.warn('No handlers found: "{}". Skipped.'.format(
/opt/homebrew/lib/python3.11/site-packages/torchprofile/profile.py:22: UserWarning: No handlers found: "aten::permute". Skipped.
  warnings.warn('No handlers found: "{}". Skipped.'.format(
